export const slogans = [
    "Ode an das Bier 🍺\nOh goldenes Elixier, so rein,\nIm Krug, im Glas, ein Funkelwein.\nDein Schaum wie Wolken, leicht und klar,\nEin Gruß der Götter, wunderbar.",
    "Man kann zwar 100% seines Geldes verlieren, aber man kann auch 1000% gewinnen, denke da mal drüber nach.. 🚬",
    "Ey, kann ich dir meinen neuen Song zeigen? 🎵",
    "Ich mache mir keine Sorgen darum, dass der Strom ausfällt, ich mache mir sorgen darum, dass das Bier leer wird und die Tank zu hat 🍺",
    "Bro ich hab ne geile Zeile pass auf: Was haben ein Esel, ein Pferd und ein Hund gemeinsam, ich steckte schon in allen drin, warte, die war falsch...",
    "Eigentlich bin ich ja gegen Propaganda, wenn Paganda aber Bier hat, bin ich Pro Paganda...",
    "Alerta, Alerta, Antibatista! 🚬",
    "Ich bin kein Alkoholiker, Alkohol ist Domeaniker 🍺",
    "Meine Bitch nennt mich nicht Daddy sondern Mutti, ähh, Deine Bitch! DEINE!!",
    "Ich jag mich hoch am Opernplatz da hat man dann für zwei Opern platz, nein das ist zu hart, das mach ich wieder weg..",
    "was haben ein Rabbi, ein Priester, ein Koch mit 3 Eiern Ein Flyerverteiler mit ei'm Paket FlyernEin Esel, zwei Geier, ich und 300 Freier gemeinsam? Könnten alle dein Vadder sein (Der Spruch ist unnormal scheiße Dome)",
    "Ich schnarche nicht, ich rotze den Tabak in der Nacht aus",
    "Dieser Spruch wird dich aufmuntern: 你真的翻譯出來了嗎.... Ich hab nicht gesagt, dass er Auf Deutsch ist 🙂",
    "Klopf Klopf, wer ist da?..... Anna... Anna Wer?... Anna Tür hat wer gekl..(Schussgeräusche)",
    "Aufgabe!: Trinke mit Dome einen kurzen, Dome gibt aus",
    "Aufgabe!: streichel Dome sanft durch seine Haare und sag ihm wie unfassbar süß sein kleines Vogelei ist.",
    "Es ist so schön hier... Ich glaube Herr Lich ist unter uns..",
];